# Generated by Django 5.0.2 on 2024-02-27 13:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acqux_main', '0002_article_notes_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz123', length=7, max_length=25, prefix=''),
        ),
    ]
