# Generated by Django 5.0.2 on 2024-02-28 04:54

import acqux_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acqux_main', '0004_article_author_articleseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=acqux_main.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=acqux_main.models.ArticleSeries.image_upload_to),
        ),
    ]
